### ISSUE TITLE
Convert title image to svg

### ISSUE THREAD

**Issue by danielrenninghoff** [studieren-ohne-grenzen/schlemmenohnegrenzen#1]
Title image is way too big. It needs to have a smaller filesize. Two options:

1. Use svg with transparency
2. Merge image with background and convert to jpg (without transparency)

@fellhorn

**Comment by marcelklehr** [comment]
/me waves :)

+1 for jpg -- more widespread support and guaranteed fixed visual appearance. Finding the right resolution for all devices is gonna be a problem, though.

**Comment by fellhorn** [comment]
I think it is going to be a huge thing dealing wit different solutions of jpeg. All modern browsers have enough svg support:
http://caniuse.com/#search=svg

Only IE is sometimes a big pile of shit by neglecting the correct drawing area. We can also use some easy substitution for the very old browsers. Somewhere I should have a few lines of code doing this.

**Comment by fellhorn** [comment]
https://github.com/studieren-ohne-grenzen/schlemmenohnegrenzen/commit/af31170eb73ef5f62f401773135672d1a0da362d

Another solution - the vectorized logos were even bigger than the png versions. Using srcsets now we can shrink down the size by 95% on mobile

**Comment by fellhorn** [comment]
@marcelklehr Maybe you have got a better idea for vectorization - but I think as a first solution this srcset of pngs should be enough.
