### ISSUE TITLE
Should we remove the phone number of member 2 from the mandatory fields?

### ISSUE THREAD

**Issue by fellhorn** [studieren-ohne-grenzen/schlemmenohnegrenzen#13]
Maybe it is a bit annoying collecting all this information (for the person doing the sign-up)

**Comment by marcelklehr** [comment]
What do we need the phone number(s) for?

**Comment by fellhorn** [comment]
At least one number to give it to the guests when there is something to organize or a problem with finding the house. So we need at least one number which was also enough the last few times.

**Comment by danielrenninghoff** [comment]
Ok, fixed in ee9788365273261717ab2679917b265ed5077721
