### ISSUE TITLE
SEPA confirmation via mail

### ISSUE THREAD

**Issue by fellhorn** [studieren-ohne-grenzen/schlemmenohnegrenzen#2]
I checked the website of Bundesbank. It seems like we do not have to create a pdf SEPA confirmation but should send the confirmation also via mail.
Is there a privacy issue then? The mail would go to both users so we probably should not send the whole IBAN. What do you think?
Or should we take a look which of the two team members owns the account and send the SEPA confimation only to him

**Comment by danielrenninghoff** [comment]
What I did now in 211f3ce5a3dc9774a383533bdbf7d8d2110e333e is that I only send the Lastschriftmandat to the user who signed up (email1). Since this user entered the information anyway, it makes sense to send him the lastschriftmandat. What do you think?

**Comment by fellhorn** [comment]
Yes - I fixed that. Now this user get's all information. I changed the form titles a bit to make it clear that user 1 should be the person filling the form

**Comment by danielrenninghoff** [comment]
One question: now you send the IBAN and BIC in plaintext unencrypted. Why?

**Comment by fellhorn** [comment]
I talked to Benni: We have to send the whole SEPA mandate via mail, too. Whole means including all information. My issue was that I do not want to send IBAN to both team members. Member 1 does not want member 2 to know his IBAN.
Since we made the code that way that the SEPA confirmation will only be sent to member 1 I do not see any privacy issue anymore.
Do you?

**Comment by marcelklehr** [comment]
Email is like, unencrypted, but I guess people don't care :)

**Comment by danielrenninghoff** [comment]
Yes, I'm not an expert but I don't think sending personal stuff like the IBAN unencrypted is something we should do. I don't think many websites do this actually. For example here is a screenshot from the Hochschulsport, as you can see, they censor the IBAN aswell.
![mandat](https://cloud.githubusercontent.com/assets/1737566/26764695/2f1e7954-496c-11e7-87de-c21b7bdd1482.jpg)

**Comment by fellhorn** [comment]
I just saw that SOG is also sending the whole IBAN via mail for membership fees ^^
I personally like the method of stripping down to the last n (3 <= n <= 5) digits. Would this be okay for you, too?

**Comment by danielrenninghoff** [comment]
Actually I just checked many mails (including big ones like Deutsche Bahn). THE ONLY entity that showed my full IBAN in the email was the Studieren Ohne Grenzen Mitgliederbeitrag. In my opinion we should change that.

**Comment by fellhorn** [comment]
But BIC in plaintext, okay?

**Comment by danielrenninghoff** [comment]
Ok :) by the way, right now we don't have IBAN validation at all ....

**Comment by fellhorn** [comment]
Fixed it: looks now like this:
IBAN: DE51 XXXX XXXX XXXX XXX 246
