### ISSUE TITLE
"mehr herausfinden" in sri lanka info section is a dead end

### ISSUE THREAD

**Issue by marcelklehr** [studieren-ohne-grenzen/schlemmenohnegrenzen#8]
Where was this link supposed to go? Contact details of the local group? ka.s-o-g.org?

**Comment by fellhorn** [comment]
Oh yes you are right. What would be the best spot to tell something about our project?
Site of our local group or the project site?

**Comment by marcelklehr** [comment]
I guess the local site would be for potential volunteers, perhaps the
best place for more project specific information would be
https://www.studieren-ohne-grenzen.org/projekte/sri-lanka/hintergrund/ ?
