### ISSUE TITLE
Hyperlink color is too bright

### ISSUE THREAD

**Issue by marcelklehr** [studieren-ohne-grenzen/schlemmenohnegrenzen#9]
Yellow on white or yellow on yellow is difficult to read, at least on my monitor ;)

**Comment by danielrenninghoff** [comment]
I agree. What would be a good color?

**Comment by marcelklehr** [comment]
#c39624 e.g. looks better for me and it still fits with the theme.

**Comment by marcelklehr** [comment]
Fixed.
